### ISSUE TITLE
Create a Requantize algorithm

### ISSUE THREAD

**Issue by bhillier3** [lbussell/vocc#22]

**Comment by lbussell** [comment]
The source code for Usenti's implementation of requantizing and exporting is located in this project: http://www.coranac.com/projects/#grit

**Comment by lbussell** [comment]
Make sure that there are no compiler warnings when you run the app. Also, prefer using `let` instead of `var` and return objects instead of arrays.

**Comment by JohnBeckner** [comment]
Fixed centroid destruction bug and changed output of k-means, fixed warnings from modification of palette.

Still needed: change method to find initial centroids to be deterministic.
