### ISSUE TITLE
Add way to switch between GBA modes

### ISSUE THREAD

**Issue by bhillier3** [lbussell/vocc#24]
Mode 0 (sprites), mode 4 (backgrounds), mode 3

**Comment by lbussell** [comment]
For this to be implemented, we need a pretty strict definition of what each mode implies as far as exports and color space limitations are.

**Comment by lbussell** [comment]
The application should start with no image already imported, and then force the user to choose from a menu hierarchy like the following (think: file > new > sprite > mode4 etc.):

- New
    - Sprite
        - Mode 3
        - Mode 4
        - Mode 5 (not important right now)
    - Spritesheet
        - 4 bpp
        - 8 bpp (not important right now)
    - Background
        - Mode 0
        - Mode 1 (not important right now)
        - Mode 2 (not important right now)
