### ISSUE TITLE
Color palette changes size when importing a specific image

### ISSUE THREAD

**Issue by lbussell** [lbussell/vocc#35]
This is the image in question:

![gatech.png](https://images.zenhubusercontent.com/5d9777613fe18d00011cfde9/d8be7e22-c5f9-44d4-9c26-2e25efc07bdd)

I think that the quantize algorithm returns a palette that is too large, and the palette has no restrictions on size, so it constructs and draws a palette that's too big.

**Comment by JohnBeckner** [comment]
Quantize: Limited paletteColorArray to length of 256
